import type { Category } from "./types";

type WordBank = Record<string, string>;

const bangladeshi: WordBank = {
  "Biryani": "Spiced layered rice dish",
  "Panta Bhat": "Fermented leftover rice",
  "Hilsa": "National fish of Bangladesh",
  "Fuchka": "Crispy shell with tangy water",
  "Chotpoti": "Spicy chickpea street snack",
  "Jilapi": "Orange spiral sweet",
  "Mishti Doi": "Sweet set yogurt",
  "Roshogolla": "Spongy milk ball in syrup",
  "Singara": "Fried triangular pastry",
  "Pitha": "Traditional rice cake",
  "Haleem": "Slow-cooked meat porridge",
  "Kacchi": "Dum-cooked mutton biryani",
  "Bhuna Khichuri": "Spiced lentil rice mix",
  "Lassi": "Yogurt drink sweet or salty",
  "Borhani": "Spiced yogurt drink at weddings",
  "Doi Chira": "Flattened rice with yogurt",
  "Shondesh": "Bengali milk sweet",
  "Chanachur": "Crunchy spicy snack mix",
  "Nimki": "Crispy fried flour snack",
  "Paratha": "Layered fried flatbread",
  "Cox's Bazar": "Longest sea beach",
  "Sundarbans": "Mangrove forest with tigers",
  "Lalbagh Fort": "Mughal stronghold in old Dhaka",
  "Ahsan Manzil": "Pink palace of the Nawabs",
  "Hatirjheel": "Dhaka lake and bridge area",
  "Dhaka": "Capital city of Bangladesh",
  "Sylhet": "Land of tea gardens",
  "Chittagong": "Port city and hills",
  "Sajek Valley": "Cloud-covered hilltop destination",
  "Bandarban": "Hill district in the southeast",
  "Kuakata": "Daughter of the sea",
  "Rangamati": "Lake and hills in CHT",
  "Srimangal": "Tea capital of Bangladesh",
  "Sonargaon": "Ancient capital of Bengal",
  "Mohasthangarh": "Oldest archaeological site",
  "Pohela Boishakh": "Bengali New Year celebration",
  "Rickshaw Art": "Colourful paintings on three wheelers",
  "Nakshi Kantha": "Embroidered quilt tradition",
  "Baul": "Mystic folk singers of Bengal",
  "Ekushey February": "Language movement day",
  "Salwar Kameez": "Traditional tunic and pants",
  "Mehndi": "Henna art on hands",
  "Alpona": "White rice paste floor art",
  "Durga Puja": "Hindu festival of the goddess",
  "Eid Jamat": "Congregational Eid prayer",
  "Gaye Holud": "Turmeric ceremony before wedding",
  "Muslin": "Famous fine Dhaka fabric",
  "Lungi": "Wrapped lower garment for men",
  "Gamcha": "Thin cotton towel",
  "Dhol": "Double-sided drum",
  "Shakib Al Hasan": "Bangladesh cricket all-rounder",
  "Mashrafe": "Beloved cricket captain",
  "Manna": "Legendary Dhallywood hero",
  "Humayun Ahmed": "Iconic Bengali novelist",
  "Lalon": "Mystic Baul philosopher",
  "Kazi Nazrul Islam": "Rebel poet of Bengal",
  "Rabindranath": "Nobel laureate Bengali poet",
  "Moushumi": "Popular Dhallywood actress",
  "CNG": "Auto-rickshaw three-wheeler",
  "Tempo": "Shared minibus transport",
  "Bhodro Lok": "Gentleman or respectable person",
  "Adda": "Casual hangout and chat",
  "Hartal": "Political strike day",
  "Cha": "Tea that fuels everything",
  "Mama": "Universal term for any dude",
  "Bhai": "Brother or close friend",
  "Taka": "Bangladeshi currency",
  "Onek Boro Bappar Pola": "Rich kid flexing attitude",
  "Padma Bridge": "Pride over the river",
  "Rickshaw": "Three wheeled pedal ride",
  "Jamdani": "Fine woven sari",
  "Panjabi": "Men's festive tunic",
  "Bhorta": "Mashed spicy sides",
  "Shutki": "Dried fish delicacy",
  "Tehari": "Spicy beef rice",
  "Tamim Iqbal": "Opening batsman legend",
  "Mustafizur": "Cutter master bowler",
  "Sangsad Bhaban": "Parliament building icon",
};

const spicy: WordBank = {
  "Kiss": "Lips meet lips",
  "Scandal": "Shocking news",
  "Crush": "Butterflies for someone",
  "Ex": "Used to date them",
  "Gossip": "Spilling the tea",
  "Skinny Dipping": "Swimming without clothes",
  "Flirting": "Playful teasing",
  "Blind Date": "Meeting a stranger",
  "Love Letter": "Written feelings",
  "Jealousy": "Green-eyed monster",
  "Rumor": "Unverified story",
  "Confession": "Admitting the truth",
  "Heartbreak": "Love gone wrong",
  "Rebound": "Too soon after",
  "Catfish": "Fake online person",
  "Situationship": "More than friends less than dating",
  "Walk of Shame": "Morning after trip home",
  "Pickup Line": "Cheesy opener",
  "Wingman": "Helps you score",
  "Friend Zone": "Just mates, sorry",
  "Breakup Text": "Ended by message",
  "Stalker": "Won't stop following",
  "Hickey": "Mark on the neck",
  "Side Eye": "Suspicious glance",
  "Hot Take": "Controversial opinion",
  "Caught in the Act": "Busted red-handed",
  "Tinder": "Dating app swipes",
  "Bumble": "Women message first",
  "Hinge": "Delete after marriage",
  "Raya": "Exclusive dating app",
  "Late Night Text": "Drunk message someone",
  "Sneaking Out": "Leave without permission",
  "White Lie": "Minor untruth told",
  "Betrayal": "Trust broken completely",
  "Double Life": "Two identity living",
  "Affair": "Secret romantic involvement",
  "Temptation": "Forbidden desire pull",
  "Guilty Pleasure": "Shameful enjoyment secret",
  "Exposed": "Secret revealed publicly",
  "Cancelled": "Publicly shamed boycott",
  "Receipts": "Evidence proof documentation",
  "Screenshot": "Image capture proof",
  "DM Slide": "Direct message approach",
  "Thirst Trap": "Attracting attention intentionally",
  "OnlyFans": "Subscription content platform",
  "Sugar Daddy": "Rich older man",
  "Sugar Baby": "Young money seeker",
  "Trophy Wife": "Young beautiful spouse",
  "Gold Digger": "Money motivated partner",
  "Prenup": "Marriage money agreement",
  "Divorce": "End marriage legally",
  "Paternity Test": "Father verification DNA",
  "Lie Detector": "Truth measuring machine",
  "Blackmail": "Coerce through exposure",
  "Scam": "Fraudulent money scheme",
  "Hush Money": "Silence buying payment",
  "NDA": "Confidentiality legal agreement",
  "House Arrest": "Home confined restriction",
  "Ankle Monitor": "Electronic tracking device",
  "Para'r Aunty": "Neighborhood gossip lady",
  "Biye Bari Drama": "Chaos at a wedding",
  "Secret Prem": "Hidden romance",
  "Chhaad Date": "Romance on the roof",
  "Coaching Bunker": "Skipping class to hang out",
  "Caught by Abba": "Dad walked in at the wrong time",
  "Bhabi Gossip": "Sister-in-law spilling tea",
  "Rishta": "Marriage proposal",
  "Cousin Drama": "Family politics",
  "Chapa Mara": "Flexing or exaggerating",
  "Love Triangle": "Three hearts tangled",
  "Soft Launch": "Hinting new partner online",
  "Hard Launch": "Official couple post",
  "Left on Read": "Seen but ignored",
  "Love Bombing": "Overwhelming early affection",
  "Breadcrumbing": "Tiny hope crumbs",
  "Long Distance": "Miles apart couple",
  "Office Romance": "Workplace secret love",
  "Meet the Parents": "Big family introduction",
  "Second Chance": "Trying love again",
  "Friends with Benefits": "No labels, with extras",
  "One Night Stand": "Gone before breakfast",
  "Booty Call": "Late night invite",
  "Sneaky Link": "Secret hookup nobody knows about",
  "Body Count": "The tally you never ask about politely",
  "Cuffing Season": "Winter partner hunting",
  "Talking Stage": "Not official yet",
  "Dry Texter": "One word replies",
  "Read Receipts": "They saw it, no reply",
  "Finsta": "Private second account",
  "Group Chat Leak": "Private messages go public",
  "Spill the Tea": "Tell me the gossip",
  "Strip Poker": "Lose a hand, lose a layer",
  "Truth or Drink": "Answer or take a shot",
  "Seven Minutes in Heaven": "Closet time at a party",
  "Hot Tub": "Steamy bubbles at night",
  "Lap Dance": "Private performance",
  "Strip Club": "Poles and dollar bills",
  "Sugar Mama": "Older woman who pays",
  "Toxic Ex": "The one you shouldn't text",
  "Cheating Scandal": "Caught with someone else",
  "Burner Phone": "Cheap prepaid device for secrets",
  "Secret Tattoo": "Ink your parents don't know about",
  "Fake Dating": "Pretend couple",
  "Hookup Culture": "Casual, no commitment",
  "Swipe Right": "Dating app yes",
  "Love at First Sight": "Instant attraction",
  "Making Out": "Kissing that goes on",
  "Bad Boy": "Trouble you're drawn to",
  "Player": "Dates everyone at once",
  "Homewrecker": "Breaks up a marriage",
  "Mistress": "The other woman",
  "Cougar": "Older woman, younger man",
  "Silver Fox": "Attractive older man",
  "Pillow Talk": "Whispers after",
  "Morning After": "Waking up regretting it",
  "Accidentally Liked": "Old photo, double tap, panic",
  "Reply Guy": "Always in her comments",
  "Two-Timing": "Seeing two people at once",
  "Love Island": "Villa of singles on TV",
  "Honeymoon Phase": "Early relationship bliss",
  "Cold Feet": "Second thoughts before the wedding",
  "Runaway Bride": "Left him at the altar",
  "Shotgun Wedding": "Married in a hurry",
  "Elope": "Marry in secret",
  "Secret Baby": "Child nobody knew about",
  "Ghosted": "They vanished mid conversation",
};

const partyTime: WordBank = {
  "Dancing": "Moving your body",
  "Karaoke": "Singing on stage",
  "Cake": "Sweet dessert",
  "Balloons": "Floating decorations",
  "DJ": "Plays music",
  "Confetti": "Tiny paper pieces",
  "Beer Pong": "Cups and balls",
  "Piñata": "Hit it with a stick",
  "Disco Ball": "Shiny spinning sphere",
  "Limbo": "How low can you go",
  "Photo Booth": "Say cheese",
  "Champagne": "Bubbly drink",
  "Costume": "Dress up as someone else",
  "Fireworks": "Explodes in the sky",
  "Bounce House": "Jump inside it",
  "Pool Party": "Swimsuits required",
  "Bonfire": "Outdoor flames",
  "Glow Sticks": "Snap and shine",
  "Red Cup": "Iconic party drink holder",
  "Playlist": "List of songs",
  "Shots": "Small strong drinks",
  "Keg": "Big barrel of beer",
  "Dance Floor": "Where you move",
  "Dare": "Do it, I'm challenging you",
  "Truth or Dare": "Pick one",
  "Spin the Bottle": "Round and round",
  "Conga Line": "Follow the leader",
  "Party Hat": "Pointy head decoration",
  "Sparkler": "Handheld firework",
  "Strobe Light": "Flash flash flash",
  "Fog Machine": "Makes it hazy",
  "Body Paint": "Art on skin",
  "Reggaeton": "Urban Latin sound",
  "Crowd Surfing": "Floating on hands",
  "Mosh Pit": "Aggressive dancing crowd",
  "Headbanging": "Violent head shaking",
  "Glow Paint": "Neon body art",
  "Blacklight": "Ultraviolet party lighting",
  "Laser Show": "Light beam performance",
  "VIP Section": "Exclusive roped area",
  "Guest List": "Names at door",
  "Bouncer": "Door muscle guard",
  "Tequila": "Mexican cactus liquor",
  "Margarita": "Lime salt cocktail",
  "Beer": "Hops grain beverage",
  "Wine": "Fermented grape juice",
  "Cocktail": "Mixed drink creation",
  "Rave": "All-night dance party",
  "House Party": "Home gathering celebration",
  "Frat Party": "College boy gathering",
  "Tailgate": "Parking lot pre-game",
  "Festival": "Large outdoor celebration",
  "Concert": "Live music performance",
  "Jello Shots": "Wiggly boozy dessert",
  "Flip Cup": "Drinking game relay",
  "Hangover": "Morning after feeling",
  "Afterparty": "Post-event continuation",
  "Pre-game": "Before main event",
  "Party Bus": "Mobile nightclub vehicle",
  "Limo": "Stretched fancy car",
  "Dance Off": "Competitive movement battle",
  "Microphone": "Sound amplification device",
  "Speakers": "Sound amplification boxes",
  "Finger Food": "Hand-held snacks",
  "Cupcakes": "Individual cake portions",
  "Party Favors": "Guest takeaway gifts",
  "Gift Bag": "Decorated paper container",
  "Confetti Cannon": "Explosive decoration launcher",
  "New Year's Eve": "December thirty-first",
  "Birthday": "Annual celebration day",
  "Graduation": "School completion ceremony",
  "Baby Shower": "Pregnancy celebration party",
  "Bridal Shower": "Pre-wedding female party",
  "Bachelorette": "Bride's final night",
  "Bachelor Party": "Groom's final night",
  "Tuxedo": "Formal male jacket",
  "Gown": "Fancy formal dress",
  "High Heels": "Tall women's shoes",
  "Bowtie": "Neck clothing accessory",
  "Silent Disco": "Headphones dance party",
  "Open Bar": "Free drinks all night",
  "Ice Sculpture": "Frozen art centerpiece",
  "Slow Dance": "Swaying close together",
  "Quinceañera": "Fifteenth birthday celebration",
  "Sweet Sixteen": "Teen milestone bash",
  "Housewarming": "New home celebration",
  "Potluck": "Everyone brings food",
  "Game Night": "Monopoly and snacks with friends",
  "Movie Night": "Films and snacks in",
  "Never Have I Ever": "Put a finger down",
  "Kings Cup": "Card drawing drinking game",
  "Cards Against Humanity": "Offensive fill in the blank party game",
  "Jenga": "Pull a block, don't topple it",
  "Twister": "Left hand on red",
  "Musical Chairs": "One seat short when the music stops",
  "Party Popper": "Pull the string, bang",
  "Cake Smash": "Face first into dessert",
  "Birthday Candles": "Make a wish and blow",
  "Surprise Party": "Everyone hides then shouts",
  "Ugly Sweater Party": "Festive knitwear contest",
  "Toga Party": "Bedsheet outfits",
  "Group Photo": "Everyone squeeze in",
  "Designated Driver": "The sober one with the keys",
  "Last Call": "Final drinks before closing",
  "Drunk Texting": "Regret messages at 2am",
  "Dance Battle": "Circle forms, moves get judged",
  "Wedding Crasher": "Uninvited guest at the ceremony",
  "Plus One": "Your invited guest",
  "RSVP": "Reply to the invite",
  "Dress Code": "What the invite says to wear",
  "Party Foul": "Spilling the drink on the couch",
  "Noise Complaint": "Neighbours call it in",
  "Cops Showed Up": "Blue lights end the night",
  "Bottle Service": "Sparklers and a VIP table",
  "Slip N Slide": "Wet plastic sheet, run and dive",
  "Water Balloon Fight": "Soaked in the backyard",
  "Sleepover": "Pyjamas and staying up late",
  "Pillow Fight": "Feathers everywhere",
  "Beer Olympics": "Team drinking games tournament",
  "Power Hour": "A shot every minute",
  "Icebreaker": "Awkward get to know you game",
  "Charades": "Act it out, no talking",
  "Pictionary": "Draw it, they guess",
  "Werewolf": "Village hunts the hidden killer",
  "Secret Santa": "Anonymous gift exchange",
  "Karaoke Duet": "Two mics, one song",
};

const celebrities: WordBank = {
  "Taylor Swift": "Pop singer songwriter",
  "Brad Pitt": "Hollywood leading man",
  "Beyonce": "Queen of R&B",
  "Tom Cruise": "Action movie star",
  "Lady Gaga": "Born this way",
  "Drake": "Started from the bottom",
  "Rihanna": "Umbrella singer",
  "Dwayne Johnson": "The Rock",
  "Oprah": "Talk show queen",
  "Leonardo DiCaprio": "Titanic actor",
  "Kim Kardashian": "Reality TV mogul",
  "Elon Musk": "Tech billionaire",
  "Ariana Grande": "Thank u next",
  "Chris Hemsworth": "Thor actor",
  "Zendaya": "Euphoria star",
  "Bad Bunny": "Latin reggaeton",
  "Travis Scott": "Astroworld rapper",
  "Billie Eilish": "Bad guy singer",
  "Post Malone": "Tattoo face rapper",
  "Selena Gomez": "Disney to pop",
  "Justin Bieber": "Canadian pop star",
  "Snoop Dogg": "West coast rapper",
  "Shakira": "Hips don't lie",
  "Will Smith": "Fresh prince",
  "Morgan Freeman": "Narrator voice",
  "Cardi B": "Bodak Yellow",
  "The Weeknd": "Blinding Lights",
  "Nicki Minaj": "Super Bass",
  "Ice Spice": "Munch rapper",
  "Harry Styles": "One Direction solo",
  "Tom Hanks": "Forrest running forever",
  "Meryl Streep": "Chameleon master actress",
  "Denzel Washington": "Intense action hero",
  "Julia Roberts": "Pretty woman smile",
  "Robert De Niro": "Taxi Driver icon",
  "Al Pacino": "Scarface Cuban kingpin",
  "Johnny Depp": "Eccentric quirky characters",
  "Angelina Jolie": "Powerful humanitarian mother",
  "Harrison Ford": "Han Solo pilot",
  "Samuel L. Jackson": "Purple lightsaber Jedi",
  "Scarlett Johansson": "Russian spy assassin",
  "Chris Evans": "Shield bearing soldier",
  "Robert Downey Jr": "Iron suit genius",
  "Mark Ruffalo": "Green rage monster",
  "Jeremy Renner": "Bow wielding archer",
  "Paul Rudd": "Tiny shrinking hero",
  "Brie Larson": "Cosmic powerful captain",
  "Tom Holland": "Spiderweb swinging teen",
  "Chadwick Boseman": "Black panther king",
  "Benedict Cumberbatch": "Strange mystic doctor",
  "Chris Pratt": "Space guarded raccoon",
  "Zoe Saldana": "Blue alien warrior",
  "Dave Bautista": "Tattooed alien goofball",
  "Bradley Cooper": "Silver linings coach",
  "Vin Diesel": "Fast furious family",
  "Hugh Jackman": "Clawed mutant healer",
  "Patrick Stewart": "Bald telepathic professor",
  "Ian McKellen": "Wizard ring master",
  "Ryan Reynolds": "Witty merc mouth",
  "Ryan Gosling": "Quiet notebook romantic",
  "Emma Stone": "Poor things quirky",
  "Jennifer Lawrence": "Hunger games archer",
  "Gwyneth Paltrow": "Ironman girlfriend CEO",
  "Anne Hathaway": "Miserable revolutionary woman",
  "Natalie Portman": "Padme queen warrior",
  "Mila Kunis": "Wicked witch beautiful",
  "Ashton Kutcher": "Two halves man",
  "Bruce Willis": "Hard yippee cop",
  "Sylvester Stallone": "Rocky fighting stallion",
  "Arnold Schwarzenegger": "Terminator Austrian muscle",
  "Keanu Reeves": "Red pill bullet dodger",
  "Matt Damon": "Bourne identity amnesiac",
  "Ben Affleck": "Batman cape crusader",
  "George Clooney": "Handsome smooth operator",
  "Christian Bale": "Dark knight detective",
  "Heath Ledger": "Joker laughing chaos",
  "Joaquin Phoenix": "Joker dancing clown",
  "Jared Leto": "Damaged platinum hair",
  "Margot Robbie": "Harley Quinn mallet",
  "Gal Gadot": "Wonder woman lasso",
  "Jason Momoa": "Aquaman ocean king",
  "Ezra Miller": "Flash speedster confused",
  "Henry Cavill": "Superman caped alien",
  "Ben Stiller": "Zoolander blue steel",
  "Adam Sandler": "Ridiculous comedy goofball",
  "Will Ferrell": "Elf absurd tall",
  "Steve Carell": "Paper office manager",
  "Jim Carrey": "Rubber faced comedian",
  "Robin Williams": "Genie voices many",
  "Eddie Murphy": "Shrek funny ogre",
  "Kevin Hart": "Short loud comedian",
  "Jack Black": "School band teacher",
  "Seth Rogen": "Stoned laughing guy",
  "Jonah Hill": "Superbad awkward teen",
  "Michael Cera": "Arrested development shy",
  "Jesse Eisenberg": "Facebook nerdy creator",
  "Woody Harrelson": "Zombieland cowboy hat",
  "Matthew McConaughey": "Alright alright alright",
  "Channing Tatum": "Magic Mike dancer",
  "Ryan Phillippe": "Cruel intentions rich",
  "Zac Efron": "High school musical",
  "Justin Timberlake": "Sexy back pop",
  "Bruno Mars": "Uptown funk grooves",
  "Ed Sheeran": "Red haired ginger",
  "Shawn Mendes": "Young teen heartthrob",
  "Charlie Puth": "Perfect pitch producer",
  "John Legend": "Love songs romantic",
  "Pharrell Williams": "Happy hat wearing",
  "Kanye West": "Controversial rap mogul",
  "Jay-Z": "Roc nation empire",
  "Eminem": "Slim shady rapper",
  "50 Cent": "In Da Club rapper",
  "Kendrick Lamar": "Humble rap genius",
  "J. Cole": "Forest Hills dreamer",
  "Future": "Trap beats pioneer",
  "Lil Wayne": "Cash money bling",
  "Adele": "Skyfall powerful voice",
  "Katy Perry": "Fireworks pop sensation",
  "Miley Cyrus": "Wrecking ball wild",
  "Dua Lipa": "Future nostalgia retro",
  "Doja Cat": "Viral rapper singer",
  "Megan Thee Stallion": "Hot girl summer",
  "Lizzo": "Truth hurts flute",
  "Olivia Rodrigo": "Drivers license heartbreak",
  "Billie Joe Armstrong": "Boulevard broken dreams",
  "Dave Grohl": "Foo fighters founder",
  "Kurt Cobain": "Nirvana grunge icon",
  "Freddie Mercury": "Bohemian rhapsody legend",
  "Elton John": "Rocket man legend",
  "Lionel Messi": "Argentine soccer GOAT",
  "Cristiano Ronaldo": "Siuuu soccer star",
  "LeBron James": "King of basketball",
  "Serena Williams": "Tennis grand slam queen",
  "Michael Jordan": "Six rings legend",
  "Usain Bolt": "Fastest man alive",
  "MrBeast": "Giveaway YouTube king",
  "Kylie Jenner": "Lip kit billionaire",
  "Sabrina Carpenter": "Espresso pop singer",
  "SZA": "Kill Bill R&B singer",
  "Timothée Chalamet": "Dune curly heartthrob",
  "Pedro Pascal": "Internet's favorite dad actor",
};

const moviesTv: WordBank = {
  "Breaking Bad": "Chemistry teacher gone bad",
  "Stranger Things": "Kids vs upside down",
  "Game of Thrones": "Medieval throne war",
  "The Office": "Awkward paper company",
  "Friends": "Six NYC roommates",
  "Squid Game": "Deadly playground contests",
  "Wednesday": "Gothic Addams daughter",
  "The Batman": "Dark detective hero",
  "Avengers": "Superhero team up",
  "Inception": "Dreams within dreams",
  "Interstellar": "Space travel time warp",
  "Titanic": "Ship hits iceberg",
  "Joker": "Villain origin story",
  "Parasite": "Rich vs poor twist",
  "Get Out": "Creepy sunken place",
  "Shrek": "Ogre fairy tale",
  "The Lion King": "Jungle prince returns",
  "Toy Story": "Toys come alive",
  "Finding Nemo": "Dad finds lost fish",
  "Frozen": "Ice queen sister",
  "Spider-Man": "Webslinging teenager",
  "The Godfather": "Mafia family saga",
  "Pulp Fiction": "Nonlinear crime stories",
  "Fight Club": "First rule broken",
  "The Matrix": "Red pill reality",
  "John Wick": "Dog revenge assassin",
  "Top Gun": "Fighter jet pilot",
  "Barbie": "Pink doll adventure",
  "Oppenheimer": "Atomic bomb creator",
  "Everything Everywhere": "Multiverse kung fu",
  "Succession": "Billionaire family drama",
  "Ted Lasso": "Wholesome football coach",
  "The Bear": "Chaotic restaurant kitchen",
  "Euphoria": "Teen drama neon",
  "Peaky Blinders": "British gangster caps",
  "Money Heist": "Red jumpsuit robbers",
  "Narcos": "Drug cartel empire",
  "The Witcher": "Monster hunting swordsman",
  "Arcane": "League of Legends animated",
  "One Piece": "Pirate treasure hunt",
  "Attack on Titan": "Giant wall monsters",
  "Death Note": "Write a name, they die",
  "Dragon Ball": "Spikey hair power up",
  "Demon Slayer": "Sword breathing techniques",
  "Jujutsu Kaisen": "Curse fighting students",
  "The Walking Dead": "Zombie apocalypse survival",
  "Black Mirror": "Dark tech futures",
  "Ozark": "Money laundering lake",
  "Better Call Saul": "Lawyer becomes criminal",
  "The Mandalorian": "Bounty hunter baby",
  "House of the Dragon": "Targaryen civil war",
  "Rick and Morty": "Drunk scientist grandson",
  "South Park": "Crude animated town",
  "Family Guy": "Random cutaway gags",
  "The Simpsons": "Yellow family sitcom",
  "Seinfeld": "Show about nothing",
  "How I Met Your Mother": "Long dating story",
  "Brooklyn Nine-Nine": "Funny cop precinct",
  "Parks and Rec": "Small town government",
  "Arrested Development": "Dysfunctional rich family",
  "The Hangover": "Vegas gone wrong",
  "Superbad": "Teen party quest",
  "Mean Girls": "High school cliques",
  "White Chicks": "Undercover disguise comedy",
  "Scary Movie": "Horror film parody",
  "IT": "Clown in sewer",
  "The Conjuring": "Haunted house investigators",
  "A Quiet Place": "Silence or die",
  "Hereditary": "Disturbing family curse",
  "Midsommar": "Swedish cult horror",
  "Scream": "Ghostface killer calls",
  "Halloween": "Michael Myers slasher",
  "The Exorcist": "Possessed girl classic",
  "The Shining": "Haunted hotel writer",
  "Jaws": "Giant shark attacks",
  "Jurassic Park": "Dinosaurs escape the island",
  "Harry Potter": "Wizard boy school",
  "Lord of the Rings": "Ring quest fellowship",
  "Star Wars": "Space opera lightsabers",
  "Back to the Future": "Time travel DeLorean",
  "Forrest Gump": "Box of chocolates",
  "The Truman Show": "His whole life is on TV",
  "Gladiator": "Roman arena fighter",
  "Rocky": "Underdog boxing champ",
  "Django Unchained": "Western revenge story",
  "Wolf of Wall Street": "Stock market fraud",
  "Catch Me If You Can": "Con artist chase",
  "The Social Network": "Facebook origin drama",
  "Whiplash": "Intense drumming teacher",
  "La La Land": "Musical love LA",
  "Avatar": "Blue aliens on Pandora",
  "Dune": "Desert spice worms",
  "Deadpool": "Fourth wall mercenary",
  "The Boys": "Corrupt superheroes exposed",
  "Bridgerton": "Regency romance scandal",
  "Sherlock": "Deduction detective genius",
  "Prison Break": "Tattooed escape plan",
  "Lost": "Mysterious island survivors",
  "You": "Charming stalker narrates",
  "Grey's Anatomy": "Endless hospital drama",
};

const videoGames: WordBank = {
  "Minecraft": "Build block world",
  "Fortnite": "Battle royale building",
  "GTA": "Open world crime",
  "Call of Duty": "Military shooter game",
  "Roblox": "Kids create games",
  "Among Us": "Space imposter game",
  "Mario": "Plumber saves princess",
  "Zelda": "Hero saves Hyrule",
  "Pokemon": "Catch train battle",
  "Tetris": "Falling block puzzle",
  "FIFA": "Football simulation game",
  "NBA 2K": "Basketball simulation game",
  "Madden": "American football game",
  "Rocket League": "Car soccer game",
  "Fall Guys": "Obstacle course beans",
  "Apex Legends": "Hero battle royale",
  "Valorant": "Tactical hero shooter",
  "League of Legends": "Team MOBA strategy",
  "Overwatch": "Hero team shooter",
  "CS2": "Tactical bomb defusal",
  "Elden Ring": "Open world souls",
  "Dark Souls": "Hard death repeat",
  "Skyrim": "Dragon fantasy RPG",
  "Red Dead Redemption": "Wild west cowboy",
  "God of War": "Angry dad mythology",
  "The Last of Us": "Post apocalypse survival",
  "Uncharted": "Treasure hunting adventure",
  "Horizon": "Robot dinosaur hunter",
  "Ghost of Tsushima": "Samurai open world",
  "Sekiro": "Shinobi souls combat",
  "Halo": "Space marine shooter",
  "Gears of War": "Chainsaw gun aliens",
  "Destiny": "Space looter shooter",
  "Titanfall": "Mech pilot combat",
  "Doom": "Demon slaying shooter",
  "Resident Evil": "Zombie survival horror",
  "Silent Hill": "Foggy psychological horror",
  "Five Nights at Freddy's": "Scary animatronic survival",
  "Outlast": "Run and hide horror",
  "Phasmophobia": "Ghost hunting co-op",
  "Animal Crossing": "Chill island life",
  "Stardew Valley": "Cozy pixel farming",
  "The Sims": "Life simulation game",
  "Harvest Moon": "Classic farm simulator",
  "Terraria": "2D sandbox adventure",
  "Cyberpunk 2077": "Futuristic dystopia RPG",
  "Witcher 3": "Monster hunting RPG",
  "Mass Effect": "Space choice RPG",
  "Dragon Age": "Fantasy party RPG",
  "Fallout": "Post nuclear wasteland",
  "Pac-Man": "Eat dots avoid ghosts",
  "Space Invaders": "Shoot descending aliens",
  "Donkey Kong": "Barrel jumping gorilla",
  "Sonic": "Fast blue hedgehog",
  "Street Fighter": "One on one fighting",
  "Mortal Kombat": "Violent fighting fatalities",
  "Tekken": "3D martial arts fighting",
  "Smash Bros": "Nintendo character brawl",
  "Clash Royale": "Card tower strategy",
  "Clash of Clans": "Build attack villages",
  "Candy Crush": "Match three sweets",
  "Subway Surfers": "Endless running trains",
  "Temple Run": "Endless escape from monkeys",
  "Flappy Bird": "Tap through pipes",
  "Wordle": "Daily five letter guess",
  "Wii Sports": "Motion control tennis and bowling",
  "Just Dance": "Copy the moves on screen",
  "Guitar Hero": "Plastic axe rhythm game",
  "Dance Dance Revolution": "Step arrow rhythm",
  "Beat Saber": "Slice flying blocks to music in VR",
  "Assassin's Creed": "Historical stealth parkour",
  "Far Cry": "Open world FPS",
  "Watch Dogs": "Hacker open world",
  "Splinter Cell": "Stealth espionage action",
  "Hitman": "Disguise assassination sandbox",
  "Portal": "Think with holes in walls",
  "Half-Life": "Sci-fi shooter classic",
  "Left 4 Dead": "Co-op zombie survival",
  "Garry's Mod": "Physics sandbox playground",
  "Team Fortress": "Class based cartoon shooter",
  "World of Warcraft": "Fantasy MMO classic",
  "RuneScape": "Old school MMO",
  "Final Fantasy": "JRPG epic series",
  "Kingdom Hearts": "Disney meets anime",
  "Persona": "Stylish JRPG life sim",
  "Cuphead": "Retro cartoon boss rush",
  "Hollow Knight": "Bug metroidvania adventure",
  "Celeste": "Precision mountain platformer",
  "Hades": "Roguelike Greek mythology",
  "Undertale": "Pacifist RPG adventure",
  "Angry Birds": "Slingshot versus pigs",
  "Fruit Ninja": "Swipe slicing produce",
  "Crossy Road": "Endless chicken hopping",
  "Genshin Impact": "Anime open world gacha",
  "Palworld": "Pokemon with guns",
  "Helldivers": "Spreading democracy co-op",
  "Balatro": "Poker roguelike deckbuilder",
  "Lethal Company": "Scrap collecting horror",
  "Baldur's Gate": "Dungeons and dragons RPG",
  "Geometry Dash": "Rhythm cube jumping",
};

const memesInternet: WordBank = {
  "Rizz": "Smooth charm charisma",
  "Skibidi": "Toilet head meme",
  "NPC": "Scripted basic behavior",
  "Sigma": "Lone wolf grindset",
  "Slay": "Absolutely killed it",
  "No Cap": "For real honest",
  "Bussin": "Really really good",
  "Yeet": "Throw with force",
  "Ratio": "More likes than you",
  "Bruh": "Are you serious",
  "Sus": "Acting suspicious",
  "Vibe Check": "Energy assessment test",
  "Main Character": "Center of attention",
  "Caught in 4K": "Undeniable evidence recorded",
  "OK Boomer": "Dismissing old views",
  "Karen": "Entitled complainer",
  "Chad": "Ultimate alpha male",
  "Simp": "Overly devoted person",
  "Stan": "Obsessive superfan",
  "Lowkey": "Secretly kind of",
  "Clout": "Social media influence",
  "GOAT": "Greatest of all time",
  "Drip": "Stylish outfit fashion",
  "Fit Check": "Outfit showcase moment",
  "Rent Free": "Living in your head",
  "Touch Grass": "Go outside already",
  "Understood the Assignment": "Nailed it perfectly",
  "It's Giving": "Radiating specific energy",
  "Ate and Left No Crumbs": "Absolutely devoured it",
  "Red Flag": "Warning sign danger",
  "Green Flag": "Positive good sign",
  "Ick": "Sudden turn off",
  "Beige Flag": "Weird but harmless",
  "Walking Red Flag": "Person full of warnings",
  "Gaslighting": "Making someone doubt reality",
  "Gatekeeping": "Hoarding exclusive knowledge",
  "Girl Boss": "Independent powerful woman",
  "Pick Me": "Seeking male validation",
  "Delulu": "Delusional but confident",
  "Unhinged": "Wildly unpredictable behavior",
  "Chronically Online": "Too much internet",
  "Doom Scrolling": "Endless negative browsing",
  "Brain Rot": "Too much internet damage",
  "Side Quest": "Random unexpected detour",
  "Plot Armor": "Impossibly lucky survival",
  "Villain Arc": "Going bad transformation",
  "Redemption Arc": "Becoming good again",
  "Origin Story": "How it all started",
  "Speedrun": "Completing something fast",
  "Rage Quit": "Angrily giving up",
  "Easter Egg": "Hidden secret surprise",
  "Cracked": "Insanely skilled player",
  "Rickroll": "Bait and switch song",
  "Dank Meme": "High quality humor",
  "Copypasta": "Copy pasted text block",
  "Shitpost": "Low effort chaos post",
  "Deep Fried Meme": "Over-filtered crusty image",
  "Wojak": "Feeling face drawing",
  "Pepe": "Green frog face",
  "Doge": "Such wow dog",
  "Nyan Cat": "Rainbow pop tart cat",
  "Stonks": "Ironic financial success",
  "This Is Fine": "Everything burning calmly",
  "Distracted Boyfriend": "Looking at someone else",
  "Drake Meme": "Approve disapprove format",
  "Galaxy Brain": "Absurdly big think",
  "Expanding Brain": "Increasingly wild ideas",
  "Mewing": "Jawline tongue exercise",
  "Fanum Tax": "Snack stealing tribute",
  "Gyatt": "Exclamation for curves",
  "Ohio": "Cursed American state",
  "Aura": "Invisible cool points",
  "Roman Empire": "Thing men think about",
  "Girl Dinner": "Snack plate meal",
  "Girl Math": "Justified spending logic",
  "Canon Event": "Unavoidable character moment",
  "Very Demure": "So mindful, so cutesy",
  "Hawk Tuah": "Spit on that thang",
  "Six Seven": "Number kids scream for no reason",
  "Chill Guy": "Cartoon dog who just doesn't care",
  "Italian Brainrot": "AI animals with pasta country names",
  "Tralalero Tralala": "Three legged shark in sneakers",
  "Looksmaxxing": "Grinding your jawline and skincare",
  "Goblin Mode": "Unwashed and unbothered",
  "Skill Issue": "Blame the player not the game",
  "Let Him Cook": "Give him a chance to finish",
  "Cooked": "Completely done for",
  "Crashout": "Losing it over something small",
  "Lock In": "Time to focus for real",
  "Yapping": "Talking way too much",
  "Glazing": "Over the top praise",
  "Womp Womp": "Sad trombone sound",
  "Griddy": "Football touchdown dance",
  "Hits Different": "Better than it should",
  "Sigma Grindset": "Lone wolf hustle mindset",
  "Rizzler": "Kid with charm",
  "Grimace Shake": "Purple McDonald's drink horror videos",
  "Bombastic Side Eye": "Judging glance sound",
  "POV": "You are the camera",
  "Harambe": "Gorilla the internet mourns",
  "Grumpy Cat": "Permanently unimpressed feline",
  "Crying Cat": "Teary eyed kitty picture",
  "Bing Chilling": "John Cena loves ice cream in Mandarin",
  "Cheugy": "Trying too hard to be trendy",
  "Menace": "Chaotic troublemaker",
  "Quiet Quitting": "Doing the bare minimum at work",
  "Cringe": "Second hand embarrassment",
  "Based": "Unapologetically yourself",
  "Mid": "Painfully average",
  "Sheesh": "Impressed exhale",
  "Nepo Baby": "Famous because of their parents",
  "Pookie": "Cutesy pet name",
  "Bestie": "Your closest friend",
  "Gen Z Stare": "Blank look instead of a reply",
  "Millennial Pause": "Brief silence before recording",
  "Alpha Male": "Self proclaimed pack leader",
  "Bae": "Before anyone else",
};

const places: WordBank = {
  "Airport": "Planes take off here",
  "Beach": "Sand and waves",
  "Library": "Quiet book place",
  "Hospital": "Where doctors work",
  "Museum": "Art and history",
  "Casino": "Gambling tables",
  "Zoo": "Caged animals",
  "Gym": "Lift weights here",
  "Church": "Sunday worship",
  "Prison": "Behind bars",
  "School": "Kids learn here",
  "University": "Higher education",
  "Farm": "Crops and livestock",
  "Bakery": "Fresh bread smell",
  "Bank": "Store your money",
  "Aquarium": "Fish behind glass",
  "Theater": "Live performances",
  "Stadium": "Big sports venue",
  "Submarine": "Underwater vessel",
  "Spaceship": "Flies to space",
  "Volcano": "Erupting mountain",
  "Desert": "Hot and sandy",
  "Jungle": "Dense tropical forest",
  "Castle": "Medieval fortress",
  "Lighthouse": "Guides ships at night",
  "Supermarket": "Grocery shopping",
  "Restaurant": "Eat a meal out",
  "Amusement Park": "Roller coasters",
  "Ski Resort": "Snow and slopes",
  "Cruise Ship": "Floating vacation",
  "Pyramid": "Ancient Egyptian tomb",
  "Haunted House": "Scary attraction",
  "Observatory": "Watch the stars",
  "Train Station": "All aboard",
  "Fire Station": "Red trucks here",
  "Bowling Alley": "Roll a strike",
  "Movie Theater": "Big screen popcorn",
  "Nightclub": "Dance until late",
  "Wedding": "Bride and groom",
  "Funeral Home": "Final goodbye",
  "Car Wash": "Soap and rinse",
  "Laundromat": "Wash your clothes",
  "Pet Store": "Buy a puppy",
  "Dentist": "Open your mouth",
  "Barbershop": "Get a haircut",
  "Construction Site": "Hard hats required",
  "Oil Rig": "Ocean drilling platform",
  "Space Station": "Orbiting lab",
  "North Pole": "Santa's icy home",
  "Treehouse": "Up in the branches",
  "Post Office": "Mail delivery hub",
  "Police Station": "Law enforcement base",
  "Court House": "Legal decisions made",
  "City Hall": "Government center",
  "Embassy": "Foreign country representative",
  "DMV": "Driver's license authority",
  "Border Crossing": "Country entry point",
  "Bus Station": "Public transport hub",
  "Subway Station": "Underground train stop",
  "Parking Garage": "Vehicle storage building",
  "Gas Station": "Fuel stop",
  "Car Dealership": "Vehicle sales lot",
  "Harbor": "Coastal ship anchorage",
  "Pier": "Ocean projection structure",
  "Boardwalk": "Seaside wooden walkway",
  "Tunnel": "Underground passage route",
  "Bridge": "Span over obstacle",
  "Highway": "Major interstate route",
  "Dirt Road": "Unpaved path",
  "Park": "Public recreation area",
  "Playground": "Children play equipment",
  "Campground": "Tent camping site",
  "Motel": "Budget lodging chain",
  "Hotel": "Multi-floor lodging",
  "Resort": "Vacation destination complex",
  "Hostel": "Budget shared lodging",
  "Cabin": "Rustic wooden shelter",
  "Cottage": "Small house dwelling",
  "Villa": "Luxurious estate home",
  "Mansion": "Palatial grand house",
  "Apartment": "Multi-unit building",
  "Penthouse": "Top-floor luxury",
  "Orphanage": "Children welfare facility",
  "Nursing Home": "Elder care facility",
  "Clinic": "Small health facility",
  "Pharmacy": "Medicine dispensary shop",
  "Botanical Garden": "Plant collection showcase",
  "Greenhouse": "Glass growing structure",
  "Hardware Store": "Tools supplies retail",
  "Warehouse": "Large storage building",
  "Factory": "Manufacturing production plant",
  "Mine": "Underground resource extraction",
  "Quarry": "Stone excavation pit",
  "Winery": "Wine production facility",
  "Brewery": "Beer production facility",
  "Vineyard": "Grape growing field",
  "Orchard": "Fruit tree farm",
  "Eiffel Tower": "Paris iron landmark",
  "Times Square": "NYC billboard chaos",
  "Grand Canyon": "Giant Arizona gorge",
  "Great Wall": "China's long barrier",
  "Taj Mahal": "White marble mausoleum",
  "Statue of Liberty": "Green torch lady",
  "Big Ben": "London clock tower",
  "Mount Everest": "World's highest peak",
  "Niagara Falls": "Massive border waterfall",
  "Las Vegas": "Desert casino city",
  "Paris": "City of love and lights",
  "Tokyo": "Neon capital of Japan",
  "New York": "The Big Apple",
  "London": "Red buses and rain",
  "Dubai": "Desert city of skyscrapers",
  "Rome": "Ancient empire capital",
  "Sydney": "Harbour city down under",
  "Bali": "Indonesian island getaway",
  "Hawaii": "Aloha island state",
  "Iceland": "Land of fire and ice",
  "Egypt": "Pharaohs and the Nile",
  "Antarctica": "Frozen southern continent",
  "Amazon Rainforest": "Biggest jungle on earth",
  "Sahara Desert": "Endless African sand",
  "Machu Picchu": "Inca ruins in the clouds",
  "Colosseum": "Roman gladiator arena",
  "Disneyland": "Happiest place on earth",
  "Hollywood": "Movie stars and a hillside sign",
  "Bermuda Triangle": "Ships vanish here",
  "Area 51": "Top secret alien base",
  "Atlantis": "Lost sunken city",
  "Hogwarts": "Wizard boarding school",
  "The Moon": "One giant leap",
  "Mars": "The red planet",
  "Great Barrier Reef": "Giant coral off Australia",
  "Venice": "Canals instead of roads",
  "Santorini": "White houses, blue domes",
  "Maldives": "Overwater bungalow paradise",
  "IKEA": "Flat pack furniture maze",
  "Costco": "Bulk shopping warehouse",
  "Starbucks": "Green mermaid coffee",
  "McDonald's": "Golden arches",
  "Ice Rink": "Frozen floor for skates",
  "Skate Park": "Ramps and rails",
  "Water Park": "Slides and wave pools",
  "Escape Room": "Solve puzzles to get out",
  "Trampoline Park": "Wall to wall bouncing",
  "Arcade": "Coins and claw machines",
  "Karaoke Bar": "Sing badly with friends",
  "Food Court": "Mall dining area",
  "Shopping Mall": "Stores under one roof",
  "Rooftop Bar": "Drinks with a skyline view",
  "Wax Museum": "Lifelike celebrity statues",
  "Planetarium": "Dome full of stars",
  "Vatican": "Smallest country, home of the Pope",
  "Stonehenge": "Mysterious stone circle",
  "Golden Gate Bridge": "Orange span over San Francisco Bay",
  "Mount Fuji": "Japan's sacred peak",
  "Sydney Opera House": "Sail shaped concert hall",
  "Buckingham Palace": "Where the King lives",
  "White House": "US president's home",
  "Alcatraz": "Island prison in the bay",
  "Chernobyl": "Abandoned nuclear zone",
};

const sports: WordBank = {
  "Basketball": "Dribble and dunk",
  "Soccer": "Kick the ball into the net",
  "Tennis": "Racket and a net",
  "Baseball": "Hit a home run",
  "Swimming": "Laps in the pool",
  "Golf": "Hole in one",
  "Boxing": "Punch in a ring",
  "Surfing": "Ride a wave",
  "Volleyball": "Hit over the net",
  "Hockey": "Puck on ice",
  "Skateboarding": "Tricks on a board",
  "Wrestling": "Grapple on the mat",
  "Gymnastics": "Flips and balance beam",
  "Archery": "Bow and arrow",
  "Fencing": "Sword fighting sport",
  "Skiing": "Down the snowy mountain",
  "Snowboarding": "One board on snow",
  "Rugby": "Tackle with an oval ball",
  "Cricket": "Bat and wickets",
  "Karate": "Martial arts kicks",
  "Table Tennis": "Tiny racket tiny ball",
  "Badminton": "Shuttlecock sport",
  "Rock Climbing": "Scale the wall",
  "Rowing": "Oars in water",
  "Diving": "Jump into the pool",
  "Water Polo": "Swimming and throwing",
  "Lacrosse": "Net on a stick",
  "Bowling": "Roll a heavy ball",
  "Dodgeball": "Throw and dodge",
  "Arm Wrestling": "Hand strength contest",
  "Marathon": "Long distance running race",
  "Triathlon": "Three event endurance sport",
  "Decathlon": "Ten event track competition",
  "Hurdles": "Run over barriers",
  "Long Jump": "Sprint then leap for distance",
  "High Jump": "Clear the bar backwards",
  "Triple Jump": "Hop, step, then leap",
  "Pole Vault": "Flexible stick launches you over the bar",
  "Shot Put": "Throw heavy sphere",
  "Discus": "Throw spinning disc",
  "Javelin": "Throw spear-like object",
  "Hammer Throw": "Spin and release",
  "Weightlifting": "Lift heavy barbells",
  "Powerlifting": "Squat bench deadlift",
  "Bodybuilding": "Muscle building competition",
  "Crossfit": "Mixed functional fitness",
  "Strongman": "Carry and lift",
  "Tug of War": "Pull rope competition",
  "Bouldering": "Rock climbing without ropes",
  "Mountaineering": "Climb big mountains",
  "Hiking": "Walk mountain trails",
  "Parkour": "Urban obstacle movement",
  "Bobsled": "Team in a sled down an ice chute",
  "Luge": "Feet first on ice at top speed",
  "Skeleton": "Headfirst sled racing",
  "Ice Skating": "Blades on a frozen rink",
  "Figure Skating": "Spins and jumps on ice",
  "Ice Hockey": "Pucks, sticks and fights",
  "Curling": "Sweeping stones on ice",
  "Synchronized Swimming": "Water dance performance",
  "Wakeboarding": "Boat towed board",
  "Water Skiing": "Boat pulled skis",
  "Kite Surfing": "Wind powered board",
  "Sailing": "Wind powered boats",
  "Canoeing": "Paddle canoe sport",
  "Kayaking": "Paddle kayak sport",
  "Rafting": "Group paddle boats",
  "Paddleboarding": "Stand up paddle",
  "Fishing": "Catch fish sport",
  "Equestrian": "Horse riding sport",
  "Polo": "Horse mounted ball",
  "Horse Racing": "Jockey riding races",
  "Rodeo": "Western riding events",
  "Bull Riding": "Eight seconds on an angry animal",
  "Cycling": "Pedal powered bikes",
  "Mountain Biking": "Off road dirt trails on two wheels",
  "BMX": "Small bike stunts",
  "Motocross": "Dirt bike racing",
  "Formula 1": "Fastest race cars",
  "NASCAR": "Oval stock car racing",
  "Pickleball": "Paddle net craze",
  "Padel": "Walled tennis doubles",
  "Squash": "Indoor wall racket",
  "Handball": "Throw into goal",
  "Softball": "Bigger ball baseball",
  "Kabaddi": "Raiding tag sport",
  "Sumo": "Giant wrestlers ring",
  "MMA": "Cage fighting mixed",
  "Judo": "Throwing martial art",
  "Taekwondo": "Korean kicking art",
  "Olympics": "Five rings every four years",
  "World Cup": "Planet's biggest football tournament",
  "Super Bowl": "American football's big final",
  "Wimbledon": "Strawberries and grass courts",
  "Tour de France": "Three weeks of cycling",
  "NBA": "Pro basketball league",
  "NFL": "Pro American football league",
  "Ultimate Frisbee": "Disc sport with end zones",
  "Darts": "Pub board and triple twenty",
  "Billiards": "Cue and coloured balls",
  "Esports": "Pro gaming tournaments",
  "Jet Ski": "Motorbike on water",
  "Yoga": "Stretch and breathe",
  "Pilates": "Core control workout",
  "Zumba": "Dance fitness class",
  "Trampoline": "Bounce and flip",
  "Paintball": "Colourful welts",
  "Laser Tag": "Glow in the dark shooting",
  "Axe Throwing": "Hurl blades at a target",
  "Go-Karting": "Tiny cars, tight track",
  "Bungee Jumping": "Dive off with a cord",
  "Skydiving": "Jump from a plane",
  "Scuba Diving": "Tank and flippers",
  "Snorkeling": "Face down, tube up",
  "Cornhole": "Beanbags into a hole",
  "Foosball": "Spin the little men",
  "Air Hockey": "Puck floating on air",
  "Jump Rope": "Skipping fast",
  "Kickball": "Baseball with your feet",
  "Spikeball": "Round net on the ground",
  "Disc Golf": "Frisbee into baskets",
  "Cheerleading": "Pyramids and pom-poms",
  "Spin Class": "Stationary bikes, loud music",
  "Chess Boxing": "Punches between moves",
  "Tetherball": "Ball on a rope around a pole",
  "MotoGP": "Fastest bikes on the planet",
};

const techGadgets: WordBank = {
  "iPhone": "Apple's pocket device",
  "Android": "Google's mobile OS",
  "MacBook": "Apple laptop",
  "iPad": "Apple tablet",
  "AirPods": "Wireless white earbuds",
  "Apple Watch": "Wrist computer from Cupertino",
  "Smartwatch": "Wrist computer device",
  "Fitness Tracker": "Counts your steps",
  "Smartphone": "Pocket internet brick",
  "Laptop": "Portable computer",
  "Desktop": "Tower computer setup",
  "Keyboard": "Type with this",
  "Mouse": "Click pointer device",
  "Monitor": "Computer display screen",
  "Webcam": "Video call camera",
  "Headphones": "Over-ear audio",
  "Earbuds": "In-ear audio",
  "Smart Speaker": "Talks back at home",
  "Alexa": "Amazon's voice helper",
  "Siri": "Apple's voice helper",
  "Google Assistant": "Hey, the search giant's voice helper",
  "Smart TV": "Internet connected television",
  "Roku": "Streaming TV stick",
  "Chromecast": "Google streaming dongle",
  "PlayStation": "Sony game console",
  "Xbox": "Microsoft game console",
  "Nintendo Switch": "Hybrid handheld console",
  "Steam Deck": "Valve handheld PC",
  "VR Headset": "Strap on virtual goggles",
  "Drone": "Flying camera robot",
  "Robot Vacuum": "Self-driving floor cleaner",
  "GPS": "Tells you where",
  "Selfie Stick": "Extends phone reach",
  "Power Bank": "Portable phone charger",
  "Charger": "Refills your battery",
  "USB Cable": "Universal data cord",
  "Hard Drive": "Spinning data storage",
  "SSD": "Fast flash storage",
  "Cloud Storage": "Remote internet files",
  "Wi-Fi": "Wireless internet at home",
  "Bluetooth": "Short range wireless",
  "Router": "Home internet box",
  "Ethernet": "Wired network cable",
  "Two-Factor Auth": "Extra login security",
  "VPN": "Hides your location",
  "Browser": "Surf the web",
  "Search Engine": "Find anything online",
  "Email": "Digital letter inbox",
  "Password": "Secret access code",
  "Encryption": "Scrambled secret data",
  "Firewall": "Network safety barrier",
  "Antivirus": "Malware blocker software",
  "Instagram": "Photo sharing app",
  "TikTok": "Short video app",
  "Twitter": "Bird themed posts",
  "Facebook": "OG social network",
  "Snapchat": "Disappearing message app",
  "YouTube": "Video sharing giant",
  "Spotify": "Streaming music service",
  "Netflix": "Streaming movie giant",
  "Disney Plus": "Mouse house streaming",
  "Amazon": "Online shopping giant",
  "Google": "Search engine giant",
  "Microsoft": "Windows software giant",
  "Apple": "Cupertino fruit company",
  "Samsung": "Korean electronics giant",
  "Sony": "Japanese electronics maker",
  "Tesla": "Electric car maker",
  "OpenAI": "AI research company",
  "ChatGPT": "AI chatbot assistant",
  "Bitcoin": "Original cryptocurrency",
  "NFT": "Digital ownership token",
  "Metaverse": "Digital virtual world",
  "Virtual Reality": "Fully immersive digital",
  "Augmented Reality": "Layered on real world",
  "AI": "Smart machine thinking",
  "Algorithm": "Code recipe steps",
  "Hacker": "Breaks into systems",
  "Phishing": "Email scam bait",
  "Malware": "Bad software code",
  "Ransomware": "Pay or lose data",
  "App Store": "Phone software shop",
  "Open Source": "Free public code",
  "Server": "Always on computer",
  "API": "Software talks to software",
  "JavaScript": "Web browser language",
  "Python": "Snake themed language",
  "GitHub": "Code sharing site",
  "Discord": "Gamer chat platform",
  "Zoom": "Video meeting app",
  "Slack": "Work chat app",
  "Kindle": "Amazon e-book reader",
  "3D Printer": "Layer by layer maker",
  "Mechanical Keyboard": "Clicky typing keys",
  "Gaming Chair": "Racing seat for desks",
  "Smart Ring": "Finger health tracker",
  "Dash Cam": "Car incident recorder",
  "Ring Doorbell": "Camera front door",
  "Electric Scooter": "Standing powered ride",
  "Smart Fridge": "Internet connected cooler",
  "Face ID": "Look to unlock",
  "Screen Time": "Weekly report that shames you",
  "Airplane Mode": "No signal on purpose",
  "Do Not Disturb": "Silence every notification",
  "Dark Mode": "Easier on the eyes at night",
  "Low Battery": "Red bar of panic",
  "Autocorrect": "Changes what you meant",
  "Group Chat": "Everyone typing at once",
  "AirTag": "Track your lost keys",
  "Apple Vision Pro": "Pricey face computer",
  "Meta Quest": "Zuckerberg's VR headset",
  "Cybertruck": "Stainless steel pickup",
  "Starlink": "Satellites for internet",
  "Deepfake": "Fake face, real video",
  "Incognito Mode": "Private browsing tab",
  "Captcha": "Prove you're not a robot",
  "Spam Folder": "Where junk mail goes",
  "Blue Screen of Death": "Windows crashed, sad face",
  "Ctrl+Alt+Delete": "Three finger salute",
};

const disney: WordBank = {
  "Mickey Mouse": "Iconic round-eared mascot",
  "Minnie Mouse": "Polka dot bow girl",
  "Donald Duck": "Sailor suit, no pants",
  "Goofy": "Tall clumsy dog",
  "Pluto": "Mickey's pet dog",
  "Daisy Duck": "Donald's girlfriend",
  "Cinderella": "Glass slipper princess",
  "Snow White": "Seven dwarves friend",
  "Belle": "Beauty book lover",
  "Ariel": "Red-haired mermaid",
  "Mulan": "Chinese warrior daughter",
  "Jasmine": "Agrabah tiger owner",
  "Aladdin": "Street rat thief",
  "Pocahontas": "Native American princess",
  "Moana": "Pacific ocean voyager",
  "Elsa": "Ice powers queen",
  "Anna": "Frozen brave sister",
  "Olaf": "Warm hugs snowman",
  "Sven": "Frozen reindeer pal",
  "Kristoff": "Ice harvesting mountain man",
  "Rapunzel": "Long magic hair",
  "Tiana": "Frog kissing chef",
  "Merida": "Scottish archery princess",
  "Stitch": "Blue alien experiment",
  "Lilo": "Hawaiian alien adopter",
  "Simba": "Lion king cub",
  "Mufasa": "Wise lion father",
  "Scar": "Evil lion uncle",
  "Timon": "Meerkat sidekick",
  "Pumbaa": "Smelly warthog friend",
  "Nala": "Lion king lover",
  "Bambi": "Orphaned forest fawn",
  "Dumbo": "Big-eared flying elephant",
  "Peter Pan": "Forever young flier",
  "Tinkerbell": "Pixie dust fairy",
  "Captain Hook": "Pirate with a metal hand",
  "Wendy": "Neverland visitor girl",
  "Alice": "Wonderland rabbit chaser",
  "Cheshire Cat": "Grinning vanishing feline",
  "Mad Hatter": "Tea party host",
  "Buzz Lightyear": "Space ranger toy",
  "Woody": "Cowboy doll leader",
  "Jessie": "Yodeling cowgirl doll",
  "Bullseye": "Loyal toy horse",
  "Sulley": "Big blue monster",
  "Mike Wazowski": "One-eyed green monster",
  "Boo": "Tiny scared girl",
  "Nemo": "Lost clownfish son",
  "Dory": "Forgetful blue fish",
  "Marlin": "Anxious clownfish dad",
  "Crush": "Surfer dude sea turtle",
  "Wall-E": "Lonely trash robot",
  "EVE": "Sleek probe robot",
  "Remy": "Cooking sewer rat",
  "Lightning McQueen": "Red racing car",
  "Mater": "Rusty tow truck",
  "Carl Fredricksen": "Balloon house grandpa",
  "Russell": "Wilderness explorer kid",
  "Dug": "Talking golden retriever",
  "Joy": "Yellow happy emotion",
  "Sadness": "Blue tearful emotion",
  "Anger": "Red hothead emotion",
  "Fear": "Purple anxious emotion",
  "Disgust": "Green snobby emotion",
  "Maleficent": "Evil horned fairy",
  "Ursula": "Tentacled sea witch",
  "Cruella": "Dalmatian fur villain",
  "Hades": "Blue flame hair, underworld god",
  "Jafar": "Snake staff vizier",
  "Genie": "Three wishes blue",
  "Sebastian": "Crab under the sea",
  "Flounder": "Yellow fish sidekick",
  "Hercules": "Greek demigod hero",
  "Megara": "Sassy Hercules girlfriend",
  "Mowgli": "Jungle book boy",
  "Baloo": "Bear necessities friend",
  "Bagheera": "Wise jungle panther",
  "Tarzan": "Ape raised swinger",
  "Jane": "Tarzan's English love",
  "Pongo": "Dalmatian dad spotted",
  "Perdita": "Dalmatian mom spotted",
  "Lady": "Cocker spaniel romantic",
  "Tramp": "Stray dog charmer",
  "Pinocchio": "Wooden lying boy",
  "Jiminy Cricket": "Conscience top hat",
  "Mary Poppins": "Magical umbrella nanny",
  "Bruno": "We don't talk",
  "Mirabel": "Encanto glasses heroine",
  "Miguel": "Coco guitar boy",
  "Coco": "Day of the dead",
  "Encanto": "Colombian magical house",
  "Frozen": "Let it go, sister kingdom",
  "Tangled": "Long hair tower",
  "Brave": "Scottish redhead archer",
  "Zootopia": "Animal city detective",
  "Big Hero Six": "Inflatable robot Baymax",
  "Maui": "Shapeshifting demigod hook",
  "Baymax": "Inflatable healthcare robot",
  "Judy Hopps": "Bunny cop rookie",
  "Nick Wilde": "Sly fox hustler",
  "Kuzco": "Llama emperor groove",
  "Hei Hei": "Dumb chicken stowaway",
  "Gaston": "No one like him",
  "Lumiere": "Singing candlestick host",
  "Cogsworth": "Uptight talking clock",
  "Yzma": "Potion lab villainess",
};

const anime: WordBank = {
  "Naruto": "Whiskered orange ninja",
  "Sasuke": "Brooding Uchiha rival",
  "Sakura": "Pink-haired medic ninja",
  "Itachi": "Crow genjutsu brother",
  "Kakashi": "Masked silver scarecrow",
  "Jiraiya": "Toad sage pervert",
  "Hinata": "Shy byakugan girl",
  "Madara": "Legendary Uchiha villain",
  "Goku": "Spiky saiyan hero",
  "Vegeta": "Prince of saiyans",
  "Gohan": "Goku's nerd son",
  "Piccolo": "Green Namekian mentor",
  "Frieza": "Pink space tyrant",
  "Cell": "Perfect form android",
  "Majin Buu": "Pink bubblegum monster",
  "Trunks": "Time travel saiyan",
  "Luffy": "Stretchy rubber pirate",
  "Zoro": "Three sword swordsman",
  "Nami": "Orange-haired navigator",
  "Sanji": "Cook with eyebrow",
  "Chopper": "Reindeer doctor cute",
  "Robin": "Archaeologist many hands",
  "Usopp": "Long-nosed liar sniper",
  "Brook": "Singing skeleton swordsman",
  "Franky": "Cyborg super shipwright",
  "Shanks": "Red-haired emperor mentor",
  "Whitebeard": "Quake quake emperor",
  "Ace": "Fire fist brother",
  "Sabo": "Top hat brother",
  "Boa Hancock": "Snake princess beauty",
  "Doflamingo": "Pink feathered villain",
  "Kaido": "Dragon beast emperor",
  "Light Yagami": "Death note holder",
  "L": "Sweet toothed genius detective",
  "Misa": "Second Kira gothic",
  "Ryuk": "Apple loving shinigami",
  "Near": "White albino successor",
  "Mello": "Chocolate eating successor",
  "Tanjiro": "Kind hearted slayer",
  "Nezuko": "Bamboo muzzle sister",
  "Zenitsu": "Cowardly thunder breather",
  "Inosuke": "Boar mask wild",
  "Giyu": "Water hashira stoic",
  "Rengoku": "Flame hashira hero",
  "Akaza": "Upper three demon",
  "Muzan": "Demon king progenitor",
  "Yuji Itadori": "Sukuna's vessel boy",
  "Megumi": "Ten shadows guy",
  "Nobara": "Hammer nail girl",
  "Gojo": "Six eyes blindfold",
  "Sukuna": "Four armed king",
  "Mahito": "Soul reshaping villain",
  "Toji": "Sorcerer killer dad",
  "Eren": "Angry titan boy",
  "Mikasa": "Scarf wearing protector",
  "Armin": "Smart strategist friend",
  "Levi": "Humanity's strongest soldier",
  "Erwin": "Commander one arm",
  "Hange": "Titan obsessed scientist",
  "Reiner": "Armored titan traitor",
  "Annie": "Female titan blonde",
  "Edward Elric": "Short alchemist brother",
  "Alphonse": "Suit of armor",
  "Roy Mustang": "Flame alchemist colonel",
  "Saitama": "One punch baldy",
  "Genos": "Cyborg disciple young",
  "Tatsumaki": "Tornado psychic small",
  "Garou": "Hero hunter villain",
  "All Might": "Symbol of peace",
  "Deku": "One for all",
  "Bakugo": "Explosive angry blonde",
  "Todoroki": "Ice fire dual",
  "Uraraka": "Gravity zero girl",
  "Iida": "Engine legs glasses",
  "Endeavor": "Number two flame",
  "Asta": "No magic screamer",
  "Yuno": "Wind magic prodigy",
  "Denji": "Chainsaw devil hybrid",
  "Power": "Blood fiend horns",
  "Makima": "Control devil boss",
  "Aki": "Curse devil cool",
  "Pochita": "Cute chainsaw dog",
  "Spike Spiegel": "Bebop bounty hunter",
  "Vash": "Humanoid typhoon gunslinger",
  "Inuyasha": "Half demon dog",
  "Kagome": "Modern girl miko",
  "Ichigo": "Orange hair shinigami",
  "Rukia": "Petite soul reaper",
  "Aizen": "Glasses traitor captain",
  "Pikachu": "Yellow electric mouse",
  "Ash Ketchum": "Pokemon master forever",
  "Misty": "Water gym leader",
  "Brock": "Rock gym squinter",
  "Eevee": "Multi evolution fox",
  "Charizard": "Fire flying lizard",
  "Mewtwo": "Cloned psychic legend",
  "Gon": "Fishing rod hunter kid",
  "Killua": "Lightning assassin friend",
  "Hisoka": "Creepy card clown",
  "Kurapika": "Chain user avenger",
  "Jotaro": "Star platinum delinquent",
  "Dio": "Road roller vampire",
  "Lelouch": "Geass strategist prince",
  "Zero Two": "Pink horned darling",
  "Anya": "Mind reading child",
  "Loid": "Spy fake father",
  "Yor": "Assassin fake mother",
  "Rem": "Blue haired maid",
};

const fashionStyle: WordBank = {
  "Jeans": "Denim leg pants",
  "T-Shirt": "Basic short sleeve",
  "Hoodie": "Hooded comfy pullover",
  "Sweater": "Warm knit pullover",
  "Dress": "One-piece outfit",
  "Skirt": "Bottom no legs",
  "Blouse": "Light dressy top",
  "Suit": "Matching jacket pants",
  "Tie": "Neck dangle accessory",
  "Bowtie": "Neck clothing accessory",
  "Tuxedo": "Formal male jacket",
  "Scarf": "Long neck wrap",
  "Beanie": "Knit winter hat",
  "Baseball Cap": "Brimmed sport hat",
  "Sun Hat": "Wide brim shade",
  "Sunglasses": "Dark eye shades",
  "Watch": "Wrist time piece",
  "Necklace": "Neck jewelry chain",
  "Earrings": "Ear piercings dangly",
  "Bracelet": "Wrist jewelry band",
  "Ring": "Finger metal band",
  "Anklet": "Ankle jewelry chain",
  "Belt": "Waist holds pants",
  "Wallet": "Money fold carrier",
  "Purse": "Small lady bag",
  "Handbag": "Carry by handle",
  "Backpack": "Two straps over the shoulders",
  "Tote Bag": "Reusable shopping bag",
  "Clutch": "Tiny handheld evening bag",
  "Sneakers": "Athletic running shoes",
  "Boots": "Tall foot covering",
  "Heels": "Tall pointy shoes",
  "Sandals": "Open toe summer",
  "Flip Flops": "Beach foam slippers",
  "Loafers": "Slip on dress",
  "Crocs": "Holey foam shoes",
  "Doc Martens": "Yellow stitch boots",
  "Air Jordans": "Michael's basketball line",
  "Yeezys": "Kanye sneaker brand",
  "Birkenstocks": "Cork sole sandals",
  "Converse": "Star canvas sneakers",
  "Vans": "Skate flat shoes",
  "Nike": "Swoosh logo brand",
  "Adidas": "Three stripes brand",
  "Puma": "Big cat brand",
  "New Balance": "Dad sneaker brand",
  "Reebok": "Classic sport brand",
  "Gucci": "Italian luxury double-G",
  "Louis Vuitton": "LV monogram bags",
  "Prada": "Italian luxury triangle",
  "Chanel": "Double-C French luxury",
  "Dior": "Paris haute couture",
  "Versace": "Medusa head Italian",
  "Burberry": "Plaid trench coat",
  "Hermes": "Birkin bag maker",
  "Rolex": "Luxury crown watches",
  "Cartier": "Love bracelet jeweler",
  "Tiffany": "Robin egg blue",
  "Calvin Klein": "Underwear basics brand",
  "Tommy Hilfiger": "Red white blue",
  "Ralph Lauren": "Polo pony brand",
  "Lacoste": "Crocodile polo brand",
  "North Face": "Outdoor gear brand",
  "Patagonia": "Eco outdoor brand",
  "Supreme": "Red box logo",
  "Off-White": "Quotation marks designer",
  "Balenciaga": "Chunky sneaker luxury",
  "Crop Top": "Belly showing shirt",
  "Bikini": "Two piece swimsuit",
  "Pajamas": "Sleepwear comfy set",
  "Robe": "Bathroom belt cover",
  "Denim Jacket": "Jeans top half",
  "Leather Jacket": "Cool biker top",
  "Trench Coat": "Long belted detective outerwear",
  "Parka": "Heavy winter coat",
  "Windbreaker": "Light shell jacket",
  "Bomber Jacket": "Pilot style zip up",
  "Cardigan": "Button up sweater",
  "Vest": "Sleeveless top layer",
  "Blazer": "Suit jacket alone",
  "Polo Shirt": "Collared top with a tiny logo",
  "Tank Top": "Sleeveless undershirt",
  "Leggings": "Tight stretchy pants",
  "Jumpsuit": "All-in-one outfit",
  "Romper": "Short jumpsuit summer",
  "Cape": "Superhero shoulder cloth",
  "Poncho": "Pull-over rain wrap",
  "Kimono": "Japanese robe wrap",
  "Sari": "Indian draped garment",
  "Hijab": "Muslim head scarf",
  "Turban": "Wrapped head cloth",
  "Tiara": "Princess head crown",
  "Zara": "Spanish fast fashion",
  "H&M": "Swedish budget clothing",
  "Shein": "Ultra cheap online hauls",
  "Uniqlo": "Japanese basics brand",
  "Lululemon": "Premium yoga wear",
  "Cargo Pants": "Pockets on the thighs",
  "Sweatpants": "Cozy lazy day",
  "Bucket Hat": "Round brim fisherman",
  "Fanny Pack": "Waist strap bag",
  "Corset": "Tight waist cincher",
};

const schoolLife: WordBank = {
  "Backpack": "Where the textbooks live",
  "Pencil": "Number two writes",
  "Eraser": "Pink mistake remover",
  "Ruler": "Measure straight line",
  "Notebook": "Lined paper bound",
  "Textbook": "Heavy class book",
  "Calculator": "Math problem solver",
  "Locker": "Hallway storage box",
  "Hall Pass": "Bathroom permission slip",
  "Field Trip": "Class outing day",
  "Recess": "Outdoor play break",
  "Cafeteria": "School food hall",
  "Detention": "After school punishment",
  "Homework": "Take home work",
  "Pop Quiz": "Surprise short test",
  "Final Exam": "End semester test",
  "Report Card": "Grade results paper",
  "Diploma": "Graduation paper proof",
  "Graduation": "Cap and gown day",
  "Class President": "Student elected leader",
  "Yearbook": "Memory photo book",
  "Prom": "Big school dance",
  "Homecoming": "Alumni return weekend",
  "Mascot": "School costume animal",
  "Pep Rally": "Spirit gym event",
  "Cheerleader": "Pom-pom waver",
  "Football Team": "School sport squad",
  "Marching Band": "Field instrument players",
  "Chess Club": "Board game group",
  "Debate Team": "Argument competition club",
  "Drama Club": "School theater group",
  "Science Fair": "Project poster board",
  "Spelling Bee": "Letter contest challenge",
  "Field Day": "Outdoor games day",
  "Substitute Teacher": "Stand in for the day",
  "Principal": "School big boss",
  "Counselor": "Schedule advice giver",
  "Janitor": "Cleans school floors",
  "School Bus": "Yellow ride home",
  "Crossing Guard": "Stop sign holder",
  "Auditorium": "Big stage room",
  "Gymnasium": "Indoor sports court",
  "Computer Lab": "Tech classroom row",
  "Science Lab": "Beaker experiment room",
  "Pizza Day": "Best lunch day",
  "Dodgeball": "Gym class, throw and duck",
  "Capture the Flag": "Team strategy game",
  "Show and Tell": "Bring share day",
  "Naptime": "Kindergarten rest break",
  "Crayon": "Wax color stick",
  "Glue Stick": "Twist paper paste",
  "Scissors": "Cutting safety tool",
  "Construction Paper": "Colored craft sheets",
  "Protractor": "Angle measure tool",
  "Compass": "Draw circles point",
  "Lab Goggles": "Eye safety glasses",
  "Bunsen Burner": "Blue flame lab",
  "Periodic Table": "Element grid chart",
  "Microscope": "Tiny thing zoom",
  "Telescope": "Far away zoom",
  "Globe": "Spinning earth ball",
  "Atlas": "Big map book",
  "Dictionary": "Word meaning book",
  "Thesaurus": "Synonym word book",
  "Algebra": "Letters in math",
  "Geometry": "Shapes and angles",
  "Calculus": "Advanced derivative math",
  "Biology": "Living things class",
  "Chemistry": "Mix and react",
  "Physics": "Force motion class",
  "History": "Past events class",
  "Geography": "World places class",
  "Spanish Class": "Hola amigo lesson",
  "Art Class": "Paint draw create",
  "Music Class": "Sing play instrument",
  "PE Class": "Gym sport period",
  "English Class": "Books grammar essays",
  "Group Project": "One person works",
  "Study Hall": "Quiet free period",
  "Tardy Slip": "Late note pass",
  "Bake Sale": "Cookie fundraiser table",
  "Lost and Found": "Forgotten item bin",
  "Valedictorian": "Top of the class",
  "Honor Roll": "Good grades list",
  "Flash Cards": "Quick memory quizzing",
  "Whiteboard": "Dry erase board",
  "Smart Board": "Touchscreen classroom display",
  "School Bell": "Class change ring",
  "Attendance": "Present or absent",
  "Gym Uniform": "PE dress code",
  "Sticky Notes": "Small paper reminders",
  "Highlighter": "Neon marking pen",
};

export const CATEGORIES: Category[] = [
  { id: "bangladeshi", name: "Bangladeshi", emoji: "🇧🇩", description: "Deshi through and through — if you know, you know. Imposters won't survive this one.", words: Object.keys(bangladeshi) },
  { id: "spicy", name: "Spicy", emoji: "🌶️", description: "Bold, cheeky, a little risky — perfect for stirring up tension and laughs.", words: Object.keys(spicy) },
  { id: "party_time", name: "Party Time", emoji: "🪩", description: "Easygoing fun with laughs and a bit of chaos — perfect for any group.", words: Object.keys(partyTime) },
  { id: "celebrities", name: "Celebrities", emoji: "⭐", description: "Famous names from movies, music, and more. Act like you're in the loop!", words: Object.keys(celebrities) },
  { id: "movies_tv", name: "Movies & TV", emoji: "🎬", description: "Blockbusters, bingeworthy shows, and iconic scenes — fake it till you make it!", words: Object.keys(moviesTv) },
  { id: "video_games", name: "Video Games", emoji: "🎮", description: "From sweaty lobbies to cozy farms — do you actually game or just watch?", words: Object.keys(videoGames) },
  { id: "memes_internet", name: "Memes & Internet", emoji: "💀", description: "Chronically online? Prove it. Brain rot has never been this fun.", words: Object.keys(memesInternet) },
  { id: "places", name: "Places", emoji: "🗽", description: "Countries, landmarks, cities — just act like you've been there!", words: Object.keys(places) },
  { id: "sports", name: "Sports", emoji: "🏀", description: "Whether you're a fan or faking it, you'll need to keep a straight face.", words: Object.keys(sports) },
  { id: "tech_gadgets", name: "Tech & Gadgets", emoji: "💻", description: "Devices, apps, and brands that run our lives — try not to glitch.", words: Object.keys(techGadgets) },
  { id: "disney", name: "Disney", emoji: "🏰", description: "Princesses, sidekicks, and villains — channel your inner Mouseketeer.", words: Object.keys(disney) },
  { id: "anime", name: "Anime", emoji: "🍙", description: "Heroes with spiky hair and tragic backstories — weebs assemble.", words: Object.keys(anime) },
  { id: "fashion_style", name: "Fashion & Style", emoji: "👗", description: "Brands, fits, and accessories — serve a look without spilling the word.", words: Object.keys(fashionStyle) },
  { id: "school_life", name: "School Life", emoji: "🎒", description: "Classes, clubs, and cafeteria chaos — relive the glory (and the trauma).", words: Object.keys(schoolLife) },
];

const HINTS_BY_CATEGORY: Record<string, WordBank> = {
  bangladeshi: bangladeshi,
  spicy: spicy,
  party_time: partyTime,
  celebrities: celebrities,
  movies_tv: moviesTv,
  video_games: videoGames,
  memes_internet: memesInternet,
  places: places,
  sports: sports,
  tech_gadgets: techGadgets,
  disney: disney,
  anime: anime,
  fashion_style: fashionStyle,
  school_life: schoolLife,
};

export function getCategoryById(id: string): Category | undefined {
  return CATEGORIES.find((c) => c.id === id);
}

export function getHintForWord(word: string, categoryId?: string | null): string {
  const own = categoryId ? HINTS_BY_CATEGORY[categoryId]?.[word] : undefined;
  if (own) return own;
  for (const bank of Object.values(HINTS_BY_CATEGORY)) {
    if (bank[word]) return bank[word];
  }
  return "No hint available";
}
